data:extend({
        {
            type = "bool-setting",
            name = "bigger-stacks",
            setting_type = "startup",
            default_value = true,
            order = "r",
			--localised_name = "Bigger material stack sizes",
			--localised_description = "If true, raw materials (ore, plates, etc) stack to 200.",
        },
        {
            type = "bool-setting",
            name = "cheap-steel",
            setting_type = "startup",
            default_value = true,
            order = "r",
			--localised_name = "Cheaper steel",
			--localised_description = "Bobplates-style; reduces cost to 2 iron per steel and halves smelt time.",
        },
        {
            type = "bool-setting",
            name = "harder-silo",
            setting_type = "startup",
            default_value = true,
            order = "r",
			--localised_name = "Harder silo",
			--localised_description = "Makes the rocket silo much harder, both in terms of research and resources.",
        },
        {
            type = "bool-setting",
            name = "manual-silo",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "harder-nuclear",
            setting_type = "startup",
            default_value = true,
            order = "r",
			--localised_name = "Harder reactors",
			--localised_description = "Greatly increases the technology progression required to research nuclear reactors.",
        },--[[
        {
            type = "bool-setting",
            name = "coal-steel",
            setting_type = "startup",
            default_value = true,
            order = "r",
			--localised_name = "Steel requires coal",
			--localised_description = "Makes the production of steel require coal as a carbon source. Steel and stone furnaces use coal anyways, but this means coal is also required for steel-making electric furnaces.",
        },--]]
        {
            type = "bool-setting",
            name = "harder-rockets",
            setting_type = "startup",
            default_value = true,
            order = "r",
			--localised_name = "Harder rockets",
			--localised_description = "Makes the rocket launches more difficult by making the resultant noise SERIOUSLY upset the local wildlife.",
        },
        {
            type = "bool-setting",
            name = "tiered-armor",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "smaller-trees",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "wood-sludging",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "advanced-satellite",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "sane-concrete",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "int-setting",
            name = "tech-demultiply",
            setting_type = "startup",
            default_value = 1,
            min_value = 1,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "split-red-science",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "tiered-bob-robots",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "cheaper-belts",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },--[[
        {
            type = "bool-setting",
            name = "split-helicopter",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },--]]
        {
            type = "bool-setting",
            name = "coal-decomposition",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "demultiply-upgrades",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "expiring-fluid",
            setting_type = "startup",
            default_value = false,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "logistics-pipes",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "steam-cracking",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "invincible-drones",
            setting_type = "startup",
            default_value = false,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "cheap-cliff-explosives",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
})
